[package]
name = "signaling-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
anyhow = "1.0.75"
tokio-tungstenite = "0.20.1"
futures-util = "0.3.28"
serde_json = "1.0.107"
